version: '3.7'

services:
  super-bot-slack:
    image: gfaraj/super-bot-slack:latest
    build: .
    hostname: superbotslack
    env_file: 
      - .env
    environment:
      NODE_ENV: development
      SUPERBOT_URL: http://host.docker.internal:3000/message
      CALLBACK_HOST: localhost
    ports:
      - 3002:3002
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 bot.js